# Generated by Django 6.0 on 2025-12-29 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Item', max_length=100)),
                ('image', models.ImageField(upload_to='wardrobe_images/')),
                ('category', models.CharField(blank=True, choices=[('Top', 'Top'), ('Bottom', 'Bottom'), ('Layer', 'Outerwear/Blazer'), ('Shoes', 'Shoes'), ('Accessory', 'Accessory')], max_length=50)),
                ('color_hex', models.CharField(default='#FFFFFF', max_length=7)),
                ('detected_material', models.CharField(default='Cotton', max_length=50)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('wear_count', models.IntegerField(default=0)),
                ('wash_count', models.IntegerField(default=0)),
                ('last_worn', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.IntegerField(default=170)),
                ('weight_kg', models.IntegerField(default=70)),
                ('skin_undertone', models.CharField(choices=[('Warm', 'Warm (Green Veins)'), ('Cool', 'Cool (Blue Veins)'), ('Neutral', 'Neutral (Mix)')], default='Neutral', max_length=20)),
                ('contrast_level', models.CharField(default='Medium', max_length=20)),
                ('season_type', models.CharField(choices=[('Winter', 'Winter'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Spring', 'Spring'), ('Unknown', 'Unknown')], default='Unknown', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
