# Generated by Django 6.0 on 2025-12-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='season_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='season',
            field=models.CharField(blank=True, choices=[('Winter', 'Winter'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Spring', 'Spring'), ('Unknown', 'Unknown')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='selfies/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contrast_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skin_undertone',
            field=models.CharField(choices=[('Blue', 'Cool (Blue Veins)'), ('Green', 'Warm (Green Veins)')], default='Green', max_length=10),
        ),
    ]
