# Generated by Django 6.0 on 2025-12-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_userprofile_season_type_userprofile_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skin_undertone',
            field=models.CharField(choices=[('Cool', 'Cool (Blue Veins)'), ('Warm', 'Warm (Green Veins)'), ('Neutral', 'Neutral (Mix/Purple)')], default='Neutral', max_length=10),
        ),
    ]
