# Generated by Django 6.0 on 2025-12-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_body_image',
            field=models.ImageField(blank=True, null=True, upload_to='body_shots/'),
        ),
    ]
