# Generated by Django 6.0 on 2026-01-14 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_userprofile_avatar_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_image', models.ImageField(upload_to='saved_outfits/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bottom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfits_bottom', to='core.garment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('top', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfits_top', to='core.garment')),
            ],
        ),
    ]
