# Generated by Django 6.0 on 2026-02-03 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_outfit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='generated_image',
        ),
        migrations.AddField(
            model_name='garment',
            name='disposal_method',
            field=models.CharField(blank=True, choices=[('Donated', 'Donated'), ('Recycled', 'Recycled'), ('Resold', 'Resold')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='garment',
            name='vton_processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='vton_garments/'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outfit',
            name='layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfits_layer', to='core.garment'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='vton_result_image',
            field=models.ImageField(blank=True, null=True, upload_to='vton_outfits/'),
        ),
    ]
