# Generated by Django 6.0 on 2026-02-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_outfit_generated_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='green_points',
            field=models.IntegerField(default=0),
        ),
    ]
